version: '3.8'

services:
  postgres_dc:
    ports:
      - "5433:5432"
    networks:
      - my_net_1

  backend:
    ports:
      - "8000:8000"
    networks:
      - my_net_1

  nginx_dc:
    ports:
      - "81:81"
    networks:
      - my_net_1


  elastic_dc:
    ports:
      - "9201:9200"
    networks:
      - my_net_1


  etl_dc:
    networks:
      - my_net_1


networks:
  my_net_1:
    driver: bridge
