version: '3.8'

services:
  backend:
    build: my_app
    container_name: backend
    ports:
      - "8000:8000"
#    expose:
#      - 8000
#    volumes:
#      - static_volume:/opt/my_app/static/
#      - media_volume:/opt/my_app/media/
    env_file:
      - .env
    depends_on:
      - postgres_dc
      - elastic_dc
    links:
      - postgres_dc
      - elastic_dc
    restart: always

  etl_dc:
    build: etl
    container_name: etl_dc
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres_dc
      - elastic_dc
      - backend
    links:
      - postgres_dc
      - elastic_dc
      - backend

  postgres_dc:
    image: postgres:14.7
    container_name: postgres_dc
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    expose:
      - 5432
#    ports:
#      - "5433:5432"
    env_file:
      - .env

  elastic_dc:
    image: elasticsearch:8.6.2
    container_name: elastic_dc
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
#    expose:
#      - 9200
    ports:
      - "9202:9200"
    restart: always

networks:
  default:
    name: nginx_proxy
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume:
